repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0 # https://github.com/pre-commit/pre-commit-hooks/releases
  hooks:
    - id: debug-statements
    - id: check-merge-conflict
    - id: trailing-whitespace
      exclude_types:
        - text
    - id: check-case-conflict
    - id: check-json
    - id: mixed-line-ending
    - id: check-yaml
      args: ["--unsafe"] # Instead of loading the files, simply parse them for syntax
- repo: https://github.com/ambv/black
  rev: 25.1.0
  hooks:
    - id: black
      name: Black
      language_version: python3.11
# - repo: local
#   hooks:
#    - id: pytest
#      name: pytest
#      entry: ./.venv/Scripts/pytest.exe
#      language: system
#      types: [python]
#      pass_filenames: false
#      always_run: true